- name: install softwares
  hosts: all
  become: true
  tasks:
    - name: install java
      yum: 
       name: java-11-openjdk
       state: latest
    
    - name: install git
      yum: 
       name: git
       state: latest