- name: install softwares
  hosts: all
  become: true
  tasks:
    - name: install java
      yum: 
       name: java-11-openjdk
       state: latest
    
    - name: install git
      yum: 
       name: git
       state: latest

    - name: install unzip
      yum:
        name: unzip
        state: latest

    - name: download and extract tomcat
      unarchive:
        src: "https://dlcdn.apache.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz"
        dest: /opt
      remote_src: True